# This compose file is compatible with Compose itself, it might need some
# adjustments to run properly with stack.

version: "3"

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: unless-stopped
    networks:
      - matrix-network
    # See the readme for a full documentation of the environment settings
    environment:
      - SYNAPSE_NO_TLS=1
      - SYNAPSE_SERVER_NAME=my.matrix.host
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./synapse-data:/data
    depends_on:
      - db
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    ports:
      - 8008:8008

  db:
    image: docker.io/postgres:13-alpine
    networks:
      - matrix-network
    # Change that password, of course!
    environment:
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: synapsetest
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'

# This setup allows for running OpenVPN and a custom dockernetwork
networks:
  matrix-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
